# Generated by Django 5.2.6 on 2025-10-29 12:59

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0008_newroadmap_roadmapstep_studentprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=250, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='chat_groups', to='student.myuser')),
                ('users_online', models.ManyToManyField(blank=True, related_name='users_online', to='student.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chatapp.chatgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='student.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Groupmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.myuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chatapp.chatgroup')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
