# Generated by Django 5.2.6 on 2025-12-29 12:09

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_chatgroup_group_name_alter_groupinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='token',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=64, unique=True),
        ),
    ]
