# Generated by Django 5.2.6 on 2025-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyparamms',
            name='iq_score',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='studyparamms',
            name='study_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
