# Generated by Django 5.2.6 on 2025-09-26 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studyparamms_iq_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_iq_quiz',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='iq_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentiqtest', to='student.myuser')),
            ],
        ),
    ]
