# Generated by Django 5.2.6 on 2025-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='iq_test',
            name='test_data',
            field=models.TextField(blank=True),
        ),
    ]
