# Generated by Django 5.2.6 on 2025-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_iq_test_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='iq_test',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
