# Generated by Django 5.2.6 on 2025-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_iq_test_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='register',
            field=models.BooleanField(default=False),
        ),
    ]
