# Generated by Django 5.2.6 on 2025-12-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_newroadmap_roadmapstep_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
