# Generated by Django 5.2.6 on 2025-12-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_compexams_examnews_newsmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrepration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.compexams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprations', to='student.myuser')),
            ],
        ),
    ]
