# Generated by Django 5.2.6 on 2025-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_userprepration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprepration',
            old_name='exm',
            new_name='exam',
        ),
        migrations.AlterField(
            model_name='compexams',
            name='name',
            field=models.CharField(choices=[('GATE', 'GATE'), ('UPSC', 'UPSC'), ('SSC', 'SSC'), ('BANKING', 'BANKING')], max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userprepration',
            unique_together={('student', 'exam')},
        ),
    ]
