# Generated by Django 5.2.6 on 2026-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_exm_userprepration_exam_alter_compexams_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
